//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace version_updater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("version_updater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл конфигурации не найден на сервере.
        /// </summary>
        internal static string ErrFileConfigNotFoundServer {
            get {
                return ResourceManager.GetString("ErrFileConfigNotFoundServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локальный файл версии пуст.
        /// </summary>
        internal static string ErrFileEmptyLocal {
            get {
                return ResourceManager.GetString("ErrFileEmptyLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл версии на сервере пуст.
        /// </summary>
        internal static string ErrFileEmptyServer {
            get {
                return ResourceManager.GetString("ErrFileEmptyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локальный файл версии не найден.
        /// </summary>
        internal static string ErrFileNotFoundLocal {
            get {
                return ResourceManager.GetString("ErrFileNotFoundLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл версии не найден на сервере.
        /// </summary>
        internal static string ErrFileNotFoundServer {
            get {
                return ResourceManager.GetString("ErrFileNotFoundServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается открыть локальный файл версии.
        /// </summary>
        internal static string ErrFileNotOpenLocal {
            get {
                return ResourceManager.GetString("ErrFileNotOpenLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается открыть файл версии на сервере.
        /// </summary>
        internal static string ErrFileNotOpenServer {
            get {
                return ResourceManager.GetString("ErrFileNotOpenServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается запустить приложение.
        /// </summary>
        internal static string ErrStartApplication {
            get {
                return ResourceManager.GetString("ErrStartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибочка.
        /// </summary>
        internal static string ErrText {
            get {
                return ResourceManager.GetString("ErrText", resourceCulture);
            }
        }
    }
}
