//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace version_updater.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("riscbinder.exe")]
        public string AfterStartApplication {
            get {
                return ((string)(this["AfterStartApplication"]));
            }
            set {
                this["AfterStartApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>common.dll</string>
  <string>components.dll</string>
  <string>data.dll</string>
  <string>ExcelTransformer.xslt</string>
  <string>ini.dll</string>
  <string>log.dll</string>
  <string>refbooks.dll</string>
  <string>riscbinder.exe</string>
  <string>RiscBinder.ini</string>
  <string>security.dll</string>
  <string>transmitters.dll</string>
  <string>version</string>
  <string>winforms.dll</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CopyFileList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CopyFileList"]));
            }
            set {
                this["CopyFileList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\dbs\\riscbinder\\distr\\")]
        public string FConfigServer {
            get {
                return ((string)(this["FConfigServer"]));
            }
            set {
                this["FConfigServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public long Version {
            get {
                return ((long)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
    }
}
